/*****************************************************************************
   can_4423__0004.h
   Generated By:
   Raptor 2021b_2.0.14465 (6183)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Jan  1 18:42:51 2023
 *****************************************************************************/

#ifndef __CAN_4423__0004_H
#define __CAN_4423__0004_H

/*   CAN Bus: CAN1 */
/*  Resource: CAN1 */

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_4423__0004(void);
extern void post_start_CAN_4423__0004(void);

/* Receive CAN object declarations */
extern uint8_T can_get_3567__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_3564__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_3560__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_3566__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_3565__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_3561__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_3562__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_3563__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_BC_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_BC_CAN1_msgID;
extern uint8_T RxTrig_XCP_BC_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_BC_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_CMD_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_CMD_CAN1_msgID;
extern uint8_T RxTrig_XCP_CMD_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_CMD_CAN1(uint16_T *age, uint32_T* id, uint8_T*
  extended, uint8_T *data, uint8_T length);
extern uint8_T can_get_uds_boot_receive_CAN1(uint16_T *age, uint32_T* id,
  uint8_T* extended, uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_3568__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_3568__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_3568__0001(uint32_T period);
extern void can_send_3569__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_3569__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_3569__0001(uint32_T period);
extern void can_send_3570__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_3570__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_3570__0001(uint32_T period);
extern void can_send_3571__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_3571__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_3571__0001(uint32_T period);
extern void can_send_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_Tx_XCP_CAN1(uint32_T period);
extern void can_send_uds_send_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_uds_send_CAN1(uint32_T id, uint8_T extended, uint8_T
  length, const uint8_T *data);
extern uint32_T can_set_period_uds_send_CAN1(uint32_T period);

#endif
