/*****************************************************************************
   can_4423__0004.c
   Generated By:
   Raptor 2021b_2.0.14465 (6183)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Jan  1 18:42:51 2023
 *****************************************************************************/

/* CAN interface: CAN1 */
/*   HW Resource: CAN1 */
#include "A1_Test.h"
#include "can_4423__0004.h"
#include "sdk_can.h"
#define MAX_AGE                        65535

int started_4423__0004 = 0;
const uint32_T CAN_CAN1_baud_rate = 500000;
uint32_T CAN_CAN1_get_baud_rate(void)
{
  return(CAN_CAN1_baud_rate);
}

/* Message Receive data storage */
/* Block: <S1>/raptor_can_rxraw8 */
void rxFn_3567__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_3567__0001[1U][8];
uint8_T rxLen_3567__0001[1U];
uint16_T rxAge_3567__0001;
uint32_T rxID_3567__0001[1U];
uint8_T rxQHead_3567__0001 = 0;
uint8_T rxQTail_3567__0001 = 0;

/* Block: <S1>/raptor_can_rxraw4 */
void rxFn_3564__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_3564__0001[1U][8];
uint8_T rxLen_3564__0001[1U];
uint16_T rxAge_3564__0001;
uint32_T rxID_3564__0001[1U];
uint8_T rxQHead_3564__0001 = 0;
uint8_T rxQTail_3564__0001 = 0;

/* Block: <S1>/raptor_can_rxraw */
void rxFn_3560__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_3560__0001[1U][8];
uint8_T rxLen_3560__0001[1U];
uint16_T rxAge_3560__0001;
uint32_T rxID_3560__0001[1U];
uint8_T rxQHead_3560__0001 = 0;
uint8_T rxQTail_3560__0001 = 0;

/* Block: <S1>/raptor_can_rxraw6 */
void rxFn_3566__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_3566__0001[1U][8];
uint8_T rxLen_3566__0001[1U];
uint16_T rxAge_3566__0001;
uint32_T rxID_3566__0001[1U];
uint8_T rxQHead_3566__0001 = 0;
uint8_T rxQTail_3566__0001 = 0;

/* Block: <S1>/raptor_can_rxraw5 */
void rxFn_3565__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_3565__0001[1U][8];
uint8_T rxLen_3565__0001[1U];
uint16_T rxAge_3565__0001;
uint32_T rxID_3565__0001[1U];
uint8_T rxQHead_3565__0001 = 0;
uint8_T rxQTail_3565__0001 = 0;

/* Block: <S1>/raptor_can_rxraw1 */
void rxFn_3561__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_3561__0001[1U][8];
uint8_T rxLen_3561__0001[1U];
uint16_T rxAge_3561__0001;
uint32_T rxID_3561__0001[1U];
uint8_T rxQHead_3561__0001 = 0;
uint8_T rxQTail_3561__0001 = 0;

/* Block: <S1>/raptor_can_rxraw2 */
void rxFn_3562__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_3562__0001[1U][8];
uint8_T rxLen_3562__0001[1U];
uint16_T rxAge_3562__0001;
uint32_T rxID_3562__0001[1U];
uint8_T rxQHead_3562__0001 = 0;
uint8_T rxQTail_3562__0001 = 0;

/* Block: <S1>/raptor_can_rxraw3 */
void rxFn_3563__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_3563__0001[1U][8];
uint8_T rxLen_3563__0001[1U];
uint16_T rxAge_3563__0001;
uint32_T rxID_3563__0001[1U];
uint8_T rxQHead_3563__0001 = 0;
uint8_T rxQTail_3563__0001 = 0;

/* Block: <S3>/raptor_xcp_update */
void rxFn_RxTrig_XCP_BC_CAN1(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_RxTrig_XCP_BC_CAN1[1][8];
uint8_T rxLen_RxTrig_XCP_BC_CAN1[1];
uint16_T rxAge_RxTrig_XCP_BC_CAN1;
uint32_T rxID_RxTrig_XCP_BC_CAN1[1];
uint8_T rxQHead_RxTrig_XCP_BC_CAN1 = 0;
uint8_T rxQTail_RxTrig_XCP_BC_CAN1 = 0;

/* Block: <S3>/raptor_xcp_update */
void rxFn_RxTrig_XCP_CMD_CAN1(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_RxTrig_XCP_CMD_CAN1[1][8];
uint8_T rxLen_RxTrig_XCP_CMD_CAN1[1];
uint16_T rxAge_RxTrig_XCP_CMD_CAN1;
uint32_T rxID_RxTrig_XCP_CMD_CAN1[1];
uint8_T rxQHead_RxTrig_XCP_CMD_CAN1 = 0;
uint8_T rxQTail_RxTrig_XCP_CMD_CAN1 = 0;

/* Block: UDS_Boot_receive_CAN1 */
void rxFn_uds_boot_receive_CAN1(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_uds_boot_receive_CAN1[1][8];
uint8_T rxLen_uds_boot_receive_CAN1[1];
uint16_T rxAge_uds_boot_receive_CAN1;
uint32_T rxID_uds_boot_receive_CAN1[1];
uint8_T rxQHead_uds_boot_receive_CAN1 = 0;
uint8_T rxQTail_uds_boot_receive_CAN1 = 0;

/* Transmit CAN Object Declarations */
/* <S1>/raptor_can_txmsg */
uint8_T txData_3568__0001[1U][8U];
uint32_T txID_3568__0001[1U];
uint8_T txExt_3568__0001[1U];
uint8_T txLen_3568__0001[1U];
uint8_T txQHead_3568__0001 = 0;
uint8_T txQTail_3568__0001 = 0;

/* <S1>/raptor_can_txmsg1 */
uint8_T txData_3569__0001[1U][8U];
uint32_T txID_3569__0001[1U];
uint8_T txExt_3569__0001[1U];
uint8_T txLen_3569__0001[1U];
uint8_T txQHead_3569__0001 = 0;
uint8_T txQTail_3569__0001 = 0;

/* <S1>/raptor_can_txmsg2 */
uint8_T txData_3570__0001[1U][8U];
uint32_T txID_3570__0001[1U];
uint8_T txExt_3570__0001[1U];
uint8_T txLen_3570__0001[1U];
uint8_T txQHead_3570__0001 = 0;
uint8_T txQTail_3570__0001 = 0;

/* <S1>/raptor_can_txmsg3 */
uint8_T txData_3571__0001[1U][8U];
uint32_T txID_3571__0001[1U];
uint8_T txExt_3571__0001[1U];
uint8_T txLen_3571__0001[1U];
uint8_T txQHead_3571__0001 = 0;
uint8_T txQTail_3571__0001 = 0;

/* <S3>/raptor_xcp_update */
uint8_T txData_Tx_XCP_CAN1[20U][8];
uint32_T txID_Tx_XCP_CAN1[20U];
uint8_T txExt_Tx_XCP_CAN1[20U];
uint8_T txLen_Tx_XCP_CAN1[20U];
uint8_T txQHead_Tx_XCP_CAN1 = 0;
uint8_T txQTail_Tx_XCP_CAN1 = 0;

/* UDS_send_CAN1 */
uint8_T txData_uds_send_CAN1[1][8];
uint32_T txID_uds_send_CAN1[1];
uint8_T txExt_uds_send_CAN1[1];
uint8_T txLen_uds_send_CAN1[1];
uint8_T txQHead_uds_send_CAN1 = 0;
uint8_T txQTail_uds_send_CAN1 = 0;

/* Functions */
void pre_start_CAN_4423__0004(void)
{
}                                      // end pre_start_CAN_4423__0004

void rxFn_3567__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_3567__0001[rxQHead_3567__0001][i] = b[i];
    }

    rxLen_3567__0001[rxQHead_3567__0001] = length;
    rxID_3567__0001[rxQHead_3567__0001] = id;
    if ((rxQHead_3567__0001 == rxQTail_3567__0001) && (rxAge_3567__0001 == 0))
      rxQTail_3567__0001 = (rxQTail_3567__0001 + 1) % 1U;
    if ((rxQHead_3567__0001 == (rxQTail_3567__0001 + 1)% 1U) &&
        (rxAge_3567__0001 != 0))
      rxQTail_3567__0001 = (rxQTail_3567__0001 + 1) % 1U;
    rxQHead_3567__0001 = (rxQHead_3567__0001 + 1 ) % 1U;
    rxAge_3567__0001 = 0;
  }
}

uint8_T can_get_3567__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_3567__0001;
  if (id != NULL)
    *id = rxID_3567__0001[rxQTail_3567__0001];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_3567__0001[rxQTail_3567__0001])
    length = rxLen_3567__0001[rxQTail_3567__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_3567__0001[rxQTail_3567__0001][i];
  if ((rxQHead_3567__0001 != (rxQTail_3567__0001 + 1)% 1U) && (rxAge_3567__0001 ==
       0))
    rxQTail_3567__0001 = (rxQTail_3567__0001 + 1) % 1U;
  else if (rxAge_3567__0001 < MAX_AGE)
    rxAge_3567__0001++;
  return length;
}

void rxFn_3564__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_3564__0001[rxQHead_3564__0001][i] = b[i];
    }

    rxLen_3564__0001[rxQHead_3564__0001] = length;
    rxID_3564__0001[rxQHead_3564__0001] = id;
    if ((rxQHead_3564__0001 == rxQTail_3564__0001) && (rxAge_3564__0001 == 0))
      rxQTail_3564__0001 = (rxQTail_3564__0001 + 1) % 1U;
    if ((rxQHead_3564__0001 == (rxQTail_3564__0001 + 1)% 1U) &&
        (rxAge_3564__0001 != 0))
      rxQTail_3564__0001 = (rxQTail_3564__0001 + 1) % 1U;
    rxQHead_3564__0001 = (rxQHead_3564__0001 + 1 ) % 1U;
    rxAge_3564__0001 = 0;
  }
}

uint8_T can_get_3564__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_3564__0001;
  if (id != NULL)
    *id = rxID_3564__0001[rxQTail_3564__0001];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_3564__0001[rxQTail_3564__0001])
    length = rxLen_3564__0001[rxQTail_3564__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_3564__0001[rxQTail_3564__0001][i];
  if ((rxQHead_3564__0001 != (rxQTail_3564__0001 + 1)% 1U) && (rxAge_3564__0001 ==
       0))
    rxQTail_3564__0001 = (rxQTail_3564__0001 + 1) % 1U;
  else if (rxAge_3564__0001 < MAX_AGE)
    rxAge_3564__0001++;
  return length;
}

void rxFn_3560__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_3560__0001[rxQHead_3560__0001][i] = b[i];
    }

    rxLen_3560__0001[rxQHead_3560__0001] = length;
    rxID_3560__0001[rxQHead_3560__0001] = id;
    if ((rxQHead_3560__0001 == rxQTail_3560__0001) && (rxAge_3560__0001 == 0))
      rxQTail_3560__0001 = (rxQTail_3560__0001 + 1) % 1U;
    if ((rxQHead_3560__0001 == (rxQTail_3560__0001 + 1)% 1U) &&
        (rxAge_3560__0001 != 0))
      rxQTail_3560__0001 = (rxQTail_3560__0001 + 1) % 1U;
    rxQHead_3560__0001 = (rxQHead_3560__0001 + 1 ) % 1U;
    rxAge_3560__0001 = 0;
  }
}

uint8_T can_get_3560__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_3560__0001;
  if (id != NULL)
    *id = rxID_3560__0001[rxQTail_3560__0001];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_3560__0001[rxQTail_3560__0001])
    length = rxLen_3560__0001[rxQTail_3560__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_3560__0001[rxQTail_3560__0001][i];
  if ((rxQHead_3560__0001 != (rxQTail_3560__0001 + 1)% 1U) && (rxAge_3560__0001 ==
       0))
    rxQTail_3560__0001 = (rxQTail_3560__0001 + 1) % 1U;
  else if (rxAge_3560__0001 < MAX_AGE)
    rxAge_3560__0001++;
  return length;
}

void rxFn_3566__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_3566__0001[rxQHead_3566__0001][i] = b[i];
    }

    rxLen_3566__0001[rxQHead_3566__0001] = length;
    rxID_3566__0001[rxQHead_3566__0001] = id;
    if ((rxQHead_3566__0001 == rxQTail_3566__0001) && (rxAge_3566__0001 == 0))
      rxQTail_3566__0001 = (rxQTail_3566__0001 + 1) % 1U;
    if ((rxQHead_3566__0001 == (rxQTail_3566__0001 + 1)% 1U) &&
        (rxAge_3566__0001 != 0))
      rxQTail_3566__0001 = (rxQTail_3566__0001 + 1) % 1U;
    rxQHead_3566__0001 = (rxQHead_3566__0001 + 1 ) % 1U;
    rxAge_3566__0001 = 0;
  }
}

uint8_T can_get_3566__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_3566__0001;
  if (id != NULL)
    *id = rxID_3566__0001[rxQTail_3566__0001];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_3566__0001[rxQTail_3566__0001])
    length = rxLen_3566__0001[rxQTail_3566__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_3566__0001[rxQTail_3566__0001][i];
  if ((rxQHead_3566__0001 != (rxQTail_3566__0001 + 1)% 1U) && (rxAge_3566__0001 ==
       0))
    rxQTail_3566__0001 = (rxQTail_3566__0001 + 1) % 1U;
  else if (rxAge_3566__0001 < MAX_AGE)
    rxAge_3566__0001++;
  return length;
}

void rxFn_3565__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_3565__0001[rxQHead_3565__0001][i] = b[i];
    }

    rxLen_3565__0001[rxQHead_3565__0001] = length;
    rxID_3565__0001[rxQHead_3565__0001] = id;
    if ((rxQHead_3565__0001 == rxQTail_3565__0001) && (rxAge_3565__0001 == 0))
      rxQTail_3565__0001 = (rxQTail_3565__0001 + 1) % 1U;
    if ((rxQHead_3565__0001 == (rxQTail_3565__0001 + 1)% 1U) &&
        (rxAge_3565__0001 != 0))
      rxQTail_3565__0001 = (rxQTail_3565__0001 + 1) % 1U;
    rxQHead_3565__0001 = (rxQHead_3565__0001 + 1 ) % 1U;
    rxAge_3565__0001 = 0;
  }
}

uint8_T can_get_3565__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_3565__0001;
  if (id != NULL)
    *id = rxID_3565__0001[rxQTail_3565__0001];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_3565__0001[rxQTail_3565__0001])
    length = rxLen_3565__0001[rxQTail_3565__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_3565__0001[rxQTail_3565__0001][i];
  if ((rxQHead_3565__0001 != (rxQTail_3565__0001 + 1)% 1U) && (rxAge_3565__0001 ==
       0))
    rxQTail_3565__0001 = (rxQTail_3565__0001 + 1) % 1U;
  else if (rxAge_3565__0001 < MAX_AGE)
    rxAge_3565__0001++;
  return length;
}

void rxFn_3561__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_3561__0001[rxQHead_3561__0001][i] = b[i];
    }

    rxLen_3561__0001[rxQHead_3561__0001] = length;
    rxID_3561__0001[rxQHead_3561__0001] = id;
    if ((rxQHead_3561__0001 == rxQTail_3561__0001) && (rxAge_3561__0001 == 0))
      rxQTail_3561__0001 = (rxQTail_3561__0001 + 1) % 1U;
    if ((rxQHead_3561__0001 == (rxQTail_3561__0001 + 1)% 1U) &&
        (rxAge_3561__0001 != 0))
      rxQTail_3561__0001 = (rxQTail_3561__0001 + 1) % 1U;
    rxQHead_3561__0001 = (rxQHead_3561__0001 + 1 ) % 1U;
    rxAge_3561__0001 = 0;
  }
}

uint8_T can_get_3561__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_3561__0001;
  if (id != NULL)
    *id = rxID_3561__0001[rxQTail_3561__0001];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_3561__0001[rxQTail_3561__0001])
    length = rxLen_3561__0001[rxQTail_3561__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_3561__0001[rxQTail_3561__0001][i];
  if ((rxQHead_3561__0001 != (rxQTail_3561__0001 + 1)% 1U) && (rxAge_3561__0001 ==
       0))
    rxQTail_3561__0001 = (rxQTail_3561__0001 + 1) % 1U;
  else if (rxAge_3561__0001 < MAX_AGE)
    rxAge_3561__0001++;
  return length;
}

void rxFn_3562__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_3562__0001[rxQHead_3562__0001][i] = b[i];
    }

    rxLen_3562__0001[rxQHead_3562__0001] = length;
    rxID_3562__0001[rxQHead_3562__0001] = id;
    if ((rxQHead_3562__0001 == rxQTail_3562__0001) && (rxAge_3562__0001 == 0))
      rxQTail_3562__0001 = (rxQTail_3562__0001 + 1) % 1U;
    if ((rxQHead_3562__0001 == (rxQTail_3562__0001 + 1)% 1U) &&
        (rxAge_3562__0001 != 0))
      rxQTail_3562__0001 = (rxQTail_3562__0001 + 1) % 1U;
    rxQHead_3562__0001 = (rxQHead_3562__0001 + 1 ) % 1U;
    rxAge_3562__0001 = 0;
  }
}

uint8_T can_get_3562__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_3562__0001;
  if (id != NULL)
    *id = rxID_3562__0001[rxQTail_3562__0001];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_3562__0001[rxQTail_3562__0001])
    length = rxLen_3562__0001[rxQTail_3562__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_3562__0001[rxQTail_3562__0001][i];
  if ((rxQHead_3562__0001 != (rxQTail_3562__0001 + 1)% 1U) && (rxAge_3562__0001 ==
       0))
    rxQTail_3562__0001 = (rxQTail_3562__0001 + 1) % 1U;
  else if (rxAge_3562__0001 < MAX_AGE)
    rxAge_3562__0001++;
  return length;
}

void rxFn_3563__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_3563__0001[rxQHead_3563__0001][i] = b[i];
    }

    rxLen_3563__0001[rxQHead_3563__0001] = length;
    rxID_3563__0001[rxQHead_3563__0001] = id;
    if ((rxQHead_3563__0001 == rxQTail_3563__0001) && (rxAge_3563__0001 == 0))
      rxQTail_3563__0001 = (rxQTail_3563__0001 + 1) % 1U;
    if ((rxQHead_3563__0001 == (rxQTail_3563__0001 + 1)% 1U) &&
        (rxAge_3563__0001 != 0))
      rxQTail_3563__0001 = (rxQTail_3563__0001 + 1) % 1U;
    rxQHead_3563__0001 = (rxQHead_3563__0001 + 1 ) % 1U;
    rxAge_3563__0001 = 0;
  }
}

uint8_T can_get_3563__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_3563__0001;
  if (id != NULL)
    *id = rxID_3563__0001[rxQTail_3563__0001];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_3563__0001[rxQTail_3563__0001])
    length = rxLen_3563__0001[rxQTail_3563__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_3563__0001[rxQTail_3563__0001][i];
  if ((rxQHead_3563__0001 != (rxQTail_3563__0001 + 1)% 1U) && (rxAge_3563__0001 ==
       0))
    rxQTail_3563__0001 = (rxQTail_3563__0001 + 1) % 1U;
  else if (rxAge_3563__0001 < MAX_AGE)
    rxAge_3563__0001++;
  return length;
}

void rxFn_RxTrig_XCP_BC_CAN1(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_RxTrig_XCP_BC_CAN1[rxQHead_RxTrig_XCP_BC_CAN1][i] = b[i];
    }

    rxLen_RxTrig_XCP_BC_CAN1[rxQHead_RxTrig_XCP_BC_CAN1] = length;
    rxID_RxTrig_XCP_BC_CAN1[rxQHead_RxTrig_XCP_BC_CAN1] = id;
    if ((rxQHead_RxTrig_XCP_BC_CAN1 == rxQTail_RxTrig_XCP_BC_CAN1) &&
        (rxAge_RxTrig_XCP_BC_CAN1 == 0))
      rxQTail_RxTrig_XCP_BC_CAN1 = (rxQTail_RxTrig_XCP_BC_CAN1 + 1) % 1;
    if ((rxQHead_RxTrig_XCP_BC_CAN1 == (rxQTail_RxTrig_XCP_BC_CAN1 + 1)% 1) &&
        (rxAge_RxTrig_XCP_BC_CAN1 != 0))
      rxQTail_RxTrig_XCP_BC_CAN1 = (rxQTail_RxTrig_XCP_BC_CAN1 + 1) % 1;
    rxQHead_RxTrig_XCP_BC_CAN1 = (rxQHead_RxTrig_XCP_BC_CAN1 + 1 ) % 1;
    rxAge_RxTrig_XCP_BC_CAN1 = 0;

    {
      extern void RxTrig_XCP_BC_CAN1();
      RxTrig_XCP_BC_CAN1();
    }
  }
}

uint32_T RxTrig_XCP_BC_CAN1_msgID = 0x100;
uint8_T RxTrig_XCP_BC_CAN1_msgExtended = 0;
void can_init_rxIdRxTrig_XCP_BC_CAN1(uint32_T id, uint8_T extended)
{
  RxTrig_XCP_BC_CAN1_msgID = id;
  RxTrig_XCP_BC_CAN1_msgExtended = extended;
}

uint8_T can_get_RxTrig_XCP_BC_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_RxTrig_XCP_BC_CAN1;
  if (id != NULL)
    *id = rxID_RxTrig_XCP_BC_CAN1[rxQTail_RxTrig_XCP_BC_CAN1];
  if (extended != NULL)
    *extended = 0;
  if (length > 8)
    length = 8;
  if (length > rxLen_RxTrig_XCP_BC_CAN1[rxQTail_RxTrig_XCP_BC_CAN1])
    length = rxLen_RxTrig_XCP_BC_CAN1[rxQTail_RxTrig_XCP_BC_CAN1];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_RxTrig_XCP_BC_CAN1[rxQTail_RxTrig_XCP_BC_CAN1][i];
  if ((rxQHead_RxTrig_XCP_BC_CAN1 != (rxQTail_RxTrig_XCP_BC_CAN1 + 1)% 1) &&
      (rxAge_RxTrig_XCP_BC_CAN1 == 0))
    rxQTail_RxTrig_XCP_BC_CAN1 = (rxQTail_RxTrig_XCP_BC_CAN1 + 1) % 1;
  else if (rxAge_RxTrig_XCP_BC_CAN1 < MAX_AGE)
    rxAge_RxTrig_XCP_BC_CAN1++;
  return length;
}

void rxFn_RxTrig_XCP_CMD_CAN1(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_RxTrig_XCP_CMD_CAN1[rxQHead_RxTrig_XCP_CMD_CAN1][i] = b[i];
    }

    rxLen_RxTrig_XCP_CMD_CAN1[rxQHead_RxTrig_XCP_CMD_CAN1] = length;
    rxID_RxTrig_XCP_CMD_CAN1[rxQHead_RxTrig_XCP_CMD_CAN1] = id;
    if ((rxQHead_RxTrig_XCP_CMD_CAN1 == rxQTail_RxTrig_XCP_CMD_CAN1) &&
        (rxAge_RxTrig_XCP_CMD_CAN1 == 0))
      rxQTail_RxTrig_XCP_CMD_CAN1 = (rxQTail_RxTrig_XCP_CMD_CAN1 + 1) % 1;
    if ((rxQHead_RxTrig_XCP_CMD_CAN1 == (rxQTail_RxTrig_XCP_CMD_CAN1 + 1)% 1) &&
        (rxAge_RxTrig_XCP_CMD_CAN1 != 0))
      rxQTail_RxTrig_XCP_CMD_CAN1 = (rxQTail_RxTrig_XCP_CMD_CAN1 + 1) % 1;
    rxQHead_RxTrig_XCP_CMD_CAN1 = (rxQHead_RxTrig_XCP_CMD_CAN1 + 1 ) % 1;
    rxAge_RxTrig_XCP_CMD_CAN1 = 0;

    {
      extern void RxTrig_XCP_CMD_CAN1();
      RxTrig_XCP_CMD_CAN1();
    }
  }
}

uint32_T RxTrig_XCP_CMD_CAN1_msgID = 0x200;
uint8_T RxTrig_XCP_CMD_CAN1_msgExtended = 0;
void can_init_rxIdRxTrig_XCP_CMD_CAN1(uint32_T id, uint8_T extended)
{
  RxTrig_XCP_CMD_CAN1_msgID = id;
  RxTrig_XCP_CMD_CAN1_msgExtended = extended;
}

uint8_T can_get_RxTrig_XCP_CMD_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_RxTrig_XCP_CMD_CAN1;
  if (id != NULL)
    *id = rxID_RxTrig_XCP_CMD_CAN1[rxQTail_RxTrig_XCP_CMD_CAN1];
  if (extended != NULL)
    *extended = 0;
  if (length > 8)
    length = 8;
  if (length > rxLen_RxTrig_XCP_CMD_CAN1[rxQTail_RxTrig_XCP_CMD_CAN1])
    length = rxLen_RxTrig_XCP_CMD_CAN1[rxQTail_RxTrig_XCP_CMD_CAN1];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_RxTrig_XCP_CMD_CAN1[rxQTail_RxTrig_XCP_CMD_CAN1][i];
  if ((rxQHead_RxTrig_XCP_CMD_CAN1 != (rxQTail_RxTrig_XCP_CMD_CAN1 + 1)% 1) &&
      (rxAge_RxTrig_XCP_CMD_CAN1 == 0))
    rxQTail_RxTrig_XCP_CMD_CAN1 = (rxQTail_RxTrig_XCP_CMD_CAN1 + 1) % 1;
  else if (rxAge_RxTrig_XCP_CMD_CAN1 < MAX_AGE)
    rxAge_RxTrig_XCP_CMD_CAN1++;
  return length;
}

void rxFn_uds_boot_receive_CAN1(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if (1 ) {
    for (i = 0; i < length; i++) {
      rxBuf_uds_boot_receive_CAN1[rxQHead_uds_boot_receive_CAN1][i] = b[i];
    }

    rxLen_uds_boot_receive_CAN1[rxQHead_uds_boot_receive_CAN1] = length;
    rxID_uds_boot_receive_CAN1[rxQHead_uds_boot_receive_CAN1] = id;
    if ((rxQHead_uds_boot_receive_CAN1 == rxQTail_uds_boot_receive_CAN1) &&
        (rxAge_uds_boot_receive_CAN1 == 0))
      rxQTail_uds_boot_receive_CAN1 = (rxQTail_uds_boot_receive_CAN1 + 1) % 1;
    if ((rxQHead_uds_boot_receive_CAN1 == (rxQTail_uds_boot_receive_CAN1 + 1)% 1)
        && (rxAge_uds_boot_receive_CAN1 != 0))
      rxQTail_uds_boot_receive_CAN1 = (rxQTail_uds_boot_receive_CAN1 + 1) % 1;
    rxQHead_uds_boot_receive_CAN1 = (rxQHead_uds_boot_receive_CAN1 + 1 ) % 1;
    rxAge_uds_boot_receive_CAN1 = 0;

    {
      extern void uds_boot_request_trigger_CAN1();
      uds_boot_request_trigger_CAN1();
    }
  }
}

uint8_T can_get_uds_boot_receive_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_uds_boot_receive_CAN1;
  if (id != NULL)
    *id = rxID_uds_boot_receive_CAN1[rxQTail_uds_boot_receive_CAN1];
  if (extended != NULL)
    *extended = 0;
  if (length > 8)
    length = 8;
  if (length > rxLen_uds_boot_receive_CAN1[rxQTail_uds_boot_receive_CAN1])
    length = rxLen_uds_boot_receive_CAN1[rxQTail_uds_boot_receive_CAN1];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_uds_boot_receive_CAN1[rxQTail_uds_boot_receive_CAN1][i];
  if ((rxQHead_uds_boot_receive_CAN1 != (rxQTail_uds_boot_receive_CAN1 + 1)% 1) &&
      (rxAge_uds_boot_receive_CAN1 == 0))
    rxQTail_uds_boot_receive_CAN1 = (rxQTail_uds_boot_receive_CAN1 + 1) % 1;
  else if (rxAge_uds_boot_receive_CAN1 < MAX_AGE)
    rxAge_uds_boot_receive_CAN1++;
  return length;
}

void can_send_3568__0001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
  if (!started_4423__0004) {
    pre_start_CAN_4423__0004();
  }

  send_can_message(CAN1, extended, id, data, length);
}

void can_update_3568__0001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
}

uint32_T can_set_period_3568__0001(uint32_T period)
{
  if (period > 65535)
    period = 65535;
  return period;
}

void can_send_3569__0001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
  if (!started_4423__0004) {
    pre_start_CAN_4423__0004();
  }

  send_can_message(CAN1, extended, id, data, length);
}

void can_update_3569__0001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
}

uint32_T can_set_period_3569__0001(uint32_T period)
{
  if (period > 65535)
    period = 65535;
  return period;
}

void can_send_3570__0001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
  if (!started_4423__0004) {
    pre_start_CAN_4423__0004();
  }

  send_can_message(CAN1, extended, id, data, length);
}

void can_update_3570__0001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
}

uint32_T can_set_period_3570__0001(uint32_T period)
{
  if (period > 65535)
    period = 65535;
  return period;
}

void can_send_3571__0001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
  if (!started_4423__0004) {
    pre_start_CAN_4423__0004();
  }

  send_can_message(CAN1, extended, id, data, length);
}

void can_update_3571__0001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
}

uint32_T can_set_period_3571__0001(uint32_T period)
{
  if (period > 65535)
    period = 65535;
  return period;
}

void can_send_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
  if (!started_4423__0004) {
    pre_start_CAN_4423__0004();
  }

  {
    extern void CAN_XCPTransmit(E_CAN_CONTROLLER busId, boolean_t extended,
      uint32_t id, uint8_t length, const uint8_t * pData);
    CAN_XCPTransmit(CAN1, extended, id, length, data);
  }
}

void can_update_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
}

uint32_T can_set_period_Tx_XCP_CAN1(uint32_T period)
{
  if (period > 65535)
    period = 65535;
  return period;
}

void can_send_uds_send_CAN1(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
  if (!started_4423__0004) {
    pre_start_CAN_4423__0004();
  }

  send_can_message(CAN1, extended, id, data, length);
}

void can_update_uds_send_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data)
{
}

uint32_T can_set_period_uds_send_CAN1(uint32_T period)
{
  if (period > 65535)
    period = 65535;
  return period;
}

void CAN_ReceiveDispatch_4423__0004(boolean extended, uint32_t id, uint8_t *
  data, uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x311) {
        rxFn_3567__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x307) {
        rxFn_3564__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x303) {
        rxFn_3560__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x309) {
        rxFn_3566__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x308) {
        rxFn_3565__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x312) {
        rxFn_3561__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x305) {
        rxFn_3562__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x306) {
        rxFn_3563__0001(id, data_len, data);
      }
    }
  }

  if (extended == 0) {
    if ((id & 0x1FFFFFFF) == (RxTrig_XCP_BC_CAN1_msgID & 0x1FFFFFFF)) {
      rxFn_RxTrig_XCP_BC_CAN1(id, data_len, data);
    }
  }

  if (extended == 0) {
    if ((id & 0x1FFFFFFF) == (RxTrig_XCP_CMD_CAN1_msgID & 0x1FFFFFFF)) {
      rxFn_RxTrig_XCP_CMD_CAN1(id, data_len, data);
    }
  }

  if (extended == 0) {
    if ((id & 0x1FFFFFFF) == (UDSServerAddr_RAM_Data() & 0x1FFFFFFF) ) {
      rxFn_uds_boot_receive_CAN1(id, data_len, data);
    }
  }
}

void post_start_CAN_4423__0004(void)
{
  if (started_4423__0004) {
    return;
  }

  started_4423__0004 = 1;
  start_CAN(CAN1, CAN_CAN1_baud_rate );
  register_receive_all_object( CAN1, CAN_ReceiveDispatch_4423__0004 );
}                                      // end post_start_CAN_4423__0004
