/*****************************************************************************
   can_4424__0004.h
   Generated By:
   Raptor 2021b_2.0.14465 (6183)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Jan  1 18:42:51 2023
 *****************************************************************************/

#ifndef __CAN_4424__0004_H
#define __CAN_4424__0004_H

/*   CAN Bus: CAN2 */
/*  Resource: CAN2 */

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_4424__0004(void);
extern void post_start_CAN_4424__0004(void);

/* Receive CAN object declarations */
extern uint8_T can_get_uds_boot_receive_CAN2(uint16_T *age, uint32_T* id,
  uint8_T* extended, uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_uds_send_CAN2(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_uds_send_CAN2(uint32_T id, uint8_T extended, uint8_T
  length, const uint8_T *data);
extern uint32_T can_set_period_uds_send_CAN2(uint32_T period);

#endif
