/*****************************************************************************
   raptor_lin_general.c
   Generated By:
   Raptor 2021b_2.0.14465 (6183)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Jan  1 18:42:51 2023
 *****************************************************************************/

#include "lin.h"

LIN_Master_Channel_t * pMaster_LIN_Defs[3] = {
  NULL,
  NULL,
  NULL,
};

LIN_Slave_Channel_t *pSlave_LIN_Def = NULL;
void Raptor_LIN_Init(void)
{
}
