/*****************************************************************************
   raptor_app.c
   Generated By:
   Raptor 2021b_2.0.14465 (6183)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Jan  1 18:42:51 2023
 *****************************************************************************/

#include "A1_Test.h"
#include "A1_Test_private.h"
#include "raptor_app.h"
#include "sdk_interface.h"
#include "mem_api.h"
#include "LTC2984_defines.h"
#include "IO_Types.h"

/*****************************************************************************
   DEFINES
 *****************************************************************************/
#define CAN_FREQUENCY                  10                        // ms
#define TIMESUB(A,B)                   ((A >= B) ? (A-B):(0xFFFFFFFF-B+1+A))

/*****************************************************************************
   GLOBALS
 *****************************************************************************/
extern EEPage0_t eepage0;

/*****************************************************************************
   CONSTANTS
 *****************************************************************************/
uint8_t app_is_in_shutdown = 0;
uint32_t g_LTC2984_DIODE_IDEALITY_FACTOR = 0x107EF9U;

/*****************************************************************************
   CAN QUEUE DEFINITONS
 *****************************************************************************/
extern void CANFrame_Queue_Create(CANFrame_Queue_t* queue, CANFrame_t data[],
  uint8_t queueSize);

/* Create global TX Queue for CAN1 */
CANFrame_t CAN1_TxQueue_data[16];
CANFrame_Queue_t g_CAN1_TxQueue;
CANFrame_t CAN1_RxQueue_data[16];
CANFrame_Queue_t g_CAN1_RxQueue;

/* Create global TX Queue for CAN2 */
CANFrame_t CAN2_TxQueue_data[16];
CANFrame_Queue_t g_CAN2_TxQueue;
CANFrame_t CAN2_RxQueue_data[16];
CANFrame_Queue_t g_CAN2_RxQueue;

/* Create global TX Queue for CAN3 */
CANFrame_t CAN3_TxQueue_data[1];
CANFrame_Queue_t g_CAN3_TxQueue;
CANFrame_t CAN3_RxQueue_data[1];
CANFrame_Queue_t g_CAN3_RxQueue;

/* Create global TX Queue for CAN4 */
CANFrame_t CAN4_TxQueue_data[1];
CANFrame_Queue_t g_CAN4_TxQueue;
CANFrame_t CAN4_RxQueue_data[1];
CANFrame_Queue_t g_CAN4_RxQueue;
S_LTC2984_CH_CONFIG LTC2984_channels[NUM_LTC2984_CH] = {
  /* CH,     ASSIGNMENT DATA, */
  { 2, SENSOR_TYPE__SENSE_RESISTOR, (uint32_t) (10000 * 1024) <<
    SENSE_RESISTOR_VALUE_LSB },

  { 4, SENSOR_TYPE__RTD_PT_200, RTD_RSENSE_CHANNEL__2 | RTD_NUM_WIRES__2_WIRE |
    RTD_EXCITATION_MODE__NO_ROTATION_SHARING | RTD_EXCITATION_CURRENT__500UA |
    RTD_STANDARD__AMERICAN },

  { 6, SENSOR_TYPE__RTD_PT_200, RTD_RSENSE_CHANNEL__2 | RTD_NUM_WIRES__2_WIRE |
    RTD_EXCITATION_MODE__NO_ROTATION_SHARING | RTD_EXCITATION_CURRENT__500UA |
    RTD_STANDARD__AMERICAN },

  { 8, SENSOR_TYPE__RTD_PT_200, RTD_RSENSE_CHANNEL__2 | RTD_NUM_WIRES__2_WIRE |
    RTD_EXCITATION_MODE__NO_ROTATION_SHARING | RTD_EXCITATION_CURRENT__500UA |
    RTD_STANDARD__AMERICAN },

  { 10, SENSOR_TYPE__RTD_PT_200, RTD_RSENSE_CHANNEL__2 | RTD_NUM_WIRES__2_WIRE |
    RTD_EXCITATION_MODE__NO_ROTATION_SHARING | RTD_EXCITATION_CURRENT__500UA |
    RTD_STANDARD__AMERICAN },

  { 12, SENSOR_TYPE__RTD_PT_200, RTD_RSENSE_CHANNEL__2 | RTD_NUM_WIRES__2_WIRE |
    RTD_EXCITATION_MODE__NO_ROTATION_SHARING | RTD_EXCITATION_CURRENT__500UA |
    RTD_STANDARD__AMERICAN },

  { 20, SENSOR_TYPE__OFF_CHIP_DIODE, DIODE_DIFFERENTIAL | DIODE_NUM_READINGS__3 |
    DIODE_AVERAGING_ON | DIODE_CURRENT__10UA_40UA_80UA },
};

/*****************************************************************************
   TIMER CALLBACK FUNCTIONS
 *****************************************************************************/
void Thread_ModelStep()
{
  if (!app_is_in_shutdown) {
    A1_Test_step();

    /* Get model outputs here */
  }
}

void Thread_Foreground()
{
  {
    Timed_Trigger_XCP();
  }

  Thread_ModelStep();

  {
    static uint32_T cnt_Foregroundx20 = (95);
    if (cnt_Foregroundx20 == 95) {
      cnt_Foregroundx20 = 0;
      if (!app_is_in_shutdown) {
        Timer_ooqlV();
      }
    } else
      cnt_Foregroundx20 += 5;
  }
}

void Thread_Background()
{
  Timer_BGND_G6Wyo();
}

/*****************************************************************************
   APPLICATION CALLBACK FUNCTIONS
 *****************************************************************************/
void App_Startup(void)
{
  app_is_in_shutdown = 0;
}

void App_Shutdown(void)
{
  app_is_in_shutdown = 1;
}

void uds_boot_request_trigger_CAN1()
{
  uint16_T age;
  uint32_T id;
  uint8_T extended;
  uint8_T data[8];
  uint16_T length = 8;
  length = can_get_uds_boot_receive_CAN1(&age, &id, &extended, data, length);
  if (length >= 3 && data[1] == 0x10 && data[2] == 0x01) {
    App_Shutdown();

    {
      extern void Reset_BootRequest( uint32_T bootaddr, uint32_T tooladdress,
        uint8_t canBus );
      Reset_BootRequest( UDSServerAddr_RAM_Data(), UDSClientAddr_RAM_Data(),
                        CAN1) ;
    }
  }
}

void uds_boot_request_trigger_CAN2()
{
  uint16_T age;
  uint32_T id;
  uint8_T extended;
  uint8_T data[8];
  uint16_T length = 8;
  length = can_get_uds_boot_receive_CAN2(&age, &id, &extended, data, length);
  if (length >= 3 && data[1] == 0x10 && data[2] == 0x01) {
    App_Shutdown();

    {
      extern void Reset_BootRequest( uint32_T bootaddr, uint32_T tooladdress,
        uint8_t canBus );
      Reset_BootRequest( UDSServerAddr_RAM_Data(), UDSClientAddr_RAM_Data(),
                        CAN2) ;
    }
  }
}

void application_int(void)
{
  initRAMVariables(&RAMVariables);
  initCONSTVariables(&CONSTVariables);

  {
    extern void App_EE_Init(void);
    App_EE_Init();
  }

  A1_Test_initialize();

  /* CAN Bus Initializations */
  CANFrame_Queue_Create(&g_CAN1_TxQueue, CAN1_TxQueue_data, (16));
  CANFrame_Queue_Create(&g_CAN1_RxQueue, CAN1_RxQueue_data, (16));
  pre_start_CAN_4423__0004();          /* <Root>/raptor_can_def */
  CANFrame_Queue_Create(&g_CAN2_TxQueue, CAN2_TxQueue_data, (16));
  CANFrame_Queue_Create(&g_CAN2_RxQueue, CAN2_RxQueue_data, (16));
  pre_start_CAN_4424__0004();          /* <Root>/raptor_can_def1 */

  /* start_CAN(); */
  post_start_CAN_4423__0004();         /* <Root>/raptor_can_def */
  post_start_CAN_4424__0004();         /* <Root>/raptor_can_def1 */
  Xcp_Initialize();

  /* Spawn Threads for timed triggers, always spawn foreground */
  add_task(&Thread_Foreground, 5, TRUE_TIMED);
  add_task(&Thread_Background, 50, TRUE_TIMED);
}
