/*****************************************************************************
   raptor_types.h
   Generated By:
   Raptor 2021b_2.0.14465 (6183)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Jan  1 18:42:51 2023
 *****************************************************************************/

#ifndef RAPTOR_TYPES_H
#define RAPTOR_TYPES_H
#include "rtwtypes.h"
#include "A1_Test_types.h"
#ifndef NULL
#define NULL                           (0)
#endif
#endif
