/*****************************************************************************
   Timer_ooqlV.c
   Generated By:
   Raptor 2021b_2.0.14465 (6183)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Jan  1 18:42:51 2023
 *****************************************************************************/

#include "A1_Test.h"
#include "A1_Test_private.h"

void Timer_ooqlV(void)
{
  /* Timer_ooqlV  ------   Foregroundx20  */
  {
    {
      A1_Test_Foreground();
    }
  }
}
